### ISSUE TITLE
Junit does not work with Eclipse after Gradle import 

### ISSUE THREAD

**Issue by seidve** [NAMI-THU/IGTPrototypingTool#2]
# Known issue: Junit in Eclipse

When importing the project (master branch) as gradle project to Eclipse (Version: 2020-12 (4.18.0)) in Windows 10, Junit tests can't be executed. An error message is displayed that the Loader class is not found:

`java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
	at org.junit.platform.launcher.core.LauncherFactory.loadAndFilterTestExecutionListeners(LauncherFactory.java:122)`

Could be an issue with Eclipse Buildship. This only happens when using Gradle 6.7.1., it still worked with Gradle 5.6.4.
Junit test can be executed when using IntelliJ (Community Edition 2020.3 on Windows 10) or command line (`gradlew.bat test`).

**Comment by seidve** [comment]
Could be resolved by explicitly adding a newer version of junit-platform-commons to gradle build file. The needed class was introduced in version 1.7.0
`testRuntimeOnly 'org.junit.platform:junit-platform-commons:1.7.2'`
Solution found here:
[https://stackoverflow.com/questions/61801256/exception-in-thread-main-java-lang-noclassdeffounderror-org-junit-platform-co](url)
